language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-20mode
  - rbx-18mode
  - rbx-19mode
  - rbx-20mode
notifications:
  recipients:
    email:
      - cedric@howe.net
  on_success: change
  on_failure: always
